version: '3.8'
services:
  db:
    container_name: postgres
    image: bitnami/postgresql
    volumes:
      - db_vol:/var/lib/postgres/data
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      - POSTGRESQL_DATABASE=apisolid
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
  api:
    container_name: api_gym
    build:
      context: .
    depends_on:
      - db
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - api_vol:/var/lib/api
    networks:
      - backend
    command: node build/server.js

networks:
  backend:
    driver: bridge

volumes:
  db_vol:
  api_vol:
